#:schema node_modules/wrangler/config-schema.json
name = "sublink-gtc"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "83c1b198f0274493b817e23ad44c67a6" }
]

[assets]
directory = "./public"
